ALTER TABLE STUDENTS RENAME COLUMN ST_ID TO STUDENT_ID;
ALTER TABLE STUDENTS ALTER COLUMN ST_NAME TYPE VARCHAR(30);
ALTER TABLE STUDENTS ALTER COLUMN ST_LAST TYPE VARCHAR(30);


ALTER TABLE INTERESTS RENAME COLUMN INTEREST TO INTERESTS;

CREATE TEMP TABLE TEMP_INTERESTS AS
SELECT
    STUDENT_ID,
   '{"' || STRING_AGG(INTERESTS, '","') || '"}' AS INTERESTS
FROM
    INTERESTS
GROUP BY
    STUDENT_ID
ORDER BY
    STUDENT_ID;

--Drop the original table
DROP TABLE INTERESTS;

-- Rename the temporary table to original table
ALTER TABLE TEMP_INTERESTS
RENAME TO INTERESTS;


Select * from INTERESTS;
select * from STUDENTS;