
ALTER TABLE STUDENTS RENAME COLUMN ST_ID TO STUDENT_ID;

ALTER TABLE STUDENTS ALTER COLUMN ST_NAME TYPE VARCHAR(30);
ALTER TABLE STUDENTS ALTER COLUMN ST_LAST TYPE VARCHAR(30);

ALTER TABLE INTERESTS RENAME COLUMN INTEREST TO INTERESTS;


Select * from INTERESTS;
