
ALTER TABLE STUDENTS RENAME COLUMN STUDENT_ID TO ST_ID;
ALTER TABLE STUDENTS ALTER COLUMN ST_NAME TYPE VARCHAR(20);
ALTER TABLE STUDENTS ALTER COLUMN ST_LAST TYPE VARCHAR(20);


ALTER TABLE INTERESTS RENAME COLUMN INTERESTS TO INTEREST;
/*ALTER TABLE INTERESTS ALTER COLUMN INTEREST TYPE VARCHAR(20);

-- Rollback the data migration
UPDATE INTERESTS SET INTEREST = INTEREST[1];

-- Drop the intermediate column
ALTER TABLE INTERESTS DROP COLUMN INTEREST;*/